# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    config:
        # Paramétrages de base
        p_annee: 2017       # Pour l'année scolaire 2017-2018
        nb_sess_req : 2     # Nombre de sessions de gonflage obligatoires
        # Répertoire utilisés
        path_photo  : "../identites/"  # Photos d'identité
        path_certif : "../certif/"
        path_fiches : "../insc/"        # Fiches d'inscription PDF
        path_fact   : "../factures/"    # Factures
        path_team   : "images/team/"
        # Fichiers de Log
        PATH_LOGS   : "/../../logs/"
        LOG_AP      :  "1"
        LOG_DB      :  "2"
        LOG_ML      :  "3"
        # Ouverture des inscriptions
        INSCR_AUCUNE   : '0'
        INSCR_PASSAGER : '1'
        INSCR_NORMAL   : '3'
        # // TODO a déplacer dans configenv
        status_inscriptions : INSCR_AUCUNE
        #status_inscriptions : 'INSCR_PASSAGER'
        #status_inscriptions : 'INSCR_NORMAL'
        # *****************************************************************/
        insc_enfants : true # false si section complete
        resp_enfants :
            "Pierre Frouin" : "pierre.frouin@neuf.fr"
        # *****************************************************************/
        insc_N1 : true # false si section complete
        resp_N1 :
            "Xavier Dupuis" : "xdupuis@gmail.com"
        # *****************************************************************/
        insc_N2 : true # false si section complete
        resp_N2 :
            "Serge Morand" : "srg.morand@sfr.fr"
        # *****************************************************************/
        insc_apnee : true # false si section complete
        resp_apnee :
            "Thierry Lamboley" : "thlamboley@laposte.net"
            "Philippe Péan"    : "phil.pean@gmail.com"
        # *****************************************************************/
        NOM_CAESUG  : "Jérôme Mars" # Nom de la personne en charge du CAESUG
        MAIL_CAESUG : "Jerome.Mars@gipsa-lab.grenoble-inp.fr" # mail de la personne en charge du CAESUG pour le GUC
        # Liens et textes affiches dans le PDF
        P_LCERTIF   : "http://www.guc-plongee.net/docs/CertMed.pdf"
        P_LAXA      : "http://www.cabinet-lafont.com/accueil/Tableau_garanties_2017-2018.pdf"
        P_BAS       : "Vous pourrez déposer votre dossier chaque Mardi, de 19h00 à 21h00, à compter du 12 Septembre à la piscine de saint martin d'Hères."
        P_BAS_PASSAGER : "Vous pourrez déposer votre dossier chaque Mardi, ou les envoyer par courrier à l'adresse indiquée dans le cartouche ci-dessus."
        DATE_DOSSIER : "12 Septembre 2017"
        # Cautions
        CAUTION_MATOS : 500 # Chèque de caution maétériel
        BADGE_PISCINE : 6   # Caution du badge d'accès piscine
        # //Fede
        LICENCE_12   : 12 # Licence moins de 12 ans (a partir de 10)
        LICENCE12_16 : 26 # Licence de 12 ans à 16 ans
        LICENCE_ADUL : 40 # Licence Adulte
        # // AXA
        AXA_L1B : 20.00 # Loisir 1 Base
        AXA_L2B : 25.00 # Loisir 2 Base
        AXA_L3B : 42.00 # Loisir 3 Base
        AXA_L1T : 39.00 # Loisir 1 Top
        AXA_L2T : 50.00 # Loisir 2 Top
        AXA_L3T : 83.00 # Loisir 3 Top
        AXA_PIS : 11.00 # Piscine
        # // Club
        CLUB_BENE : 50    # Bénévole
        CLUB_JEUN : 100   # Enfants/Etudiants
        CLUB_MAIN : 100   # Maintien
        CLUB_AUTR : 140   # Progression
        CLUB_DEBU : 100   # Débutants
        CLUB_APN1 : 100   # Nage Avec Palmes/Apnée et Plongeur Tarif 1
        CLUB_APN2 : 50    # Nage Avec Palmes/Apnée non Plongeur Tarif 2
        CARTE_GUC : 5     # Prix de la carte GUC
        # // Divers
        SIUAPS          : 22
        REDUC_FAMILLE   : 50  # Réduction pour plusieurs membres famille
        MAJO_COTISATION : 15  # Si dossier en retard
        TAXE            : 0   # Taux de taxe applicable pour les factures

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
